Add warning before overwrite file
lay295/TwitchDownloader pull request #1034
Opened 2024-04-11 17:31 UTC by atomsbaza

- Resolves #997 

TODO:
- Warning message and ReadLine input to confirm before overwriting the file

Feedback is welcomed.

2024-04-11 18:11 UTC, ScrubN commented
Thank you for the PR, however there are several issues:
1. This will only work for the CLI. As it stands, this would completely break the Windows GUI
2. Continuing on `y`, else failing is poor design in my opinion. The user should be explicitly required to confirm or reject, otherwise the program should ask again.
3. How will this work for 3rd party libraries that wrap TDCLI? They cannot reasonably work around this.
4. How will this work with status disabled? (`--log-level None`)
5. What about chat updater and chat renderer?

2024-04-12 05:44 UTC, atomsbaza commented
> Thank you for the PR, however there are several issues:
> 
> 1. This will only work for the CLI. As it stands, this would completely break the Windows GUI
> 2. Continuing on `y`, else failing is poor design in my opinion. The user should be explicitly required to confirm or reject, otherwise the program should ask again.
> 3. How will this work for 3rd party libraries that wrap TDCLI? They cannot reasonably work around this.
> 4. How will this work with status disabled? (`--log-level None`)
> 5. What about chat updater and chat renderer?

Thank you for your feedback. To answer question

1. For Windows GUI I think it isn't needed because Windows already asks to confirm before saving the file but I'm not sure that will cover all necessary because I'm using macOS so I will look for a solution again.
2. I'm gonna improve it as you ask.
3. I'm gonna looking ways to make it work. 
4. I will add more logs that can be used from ITaskLogger.
5. I will add a warning for chat updater and chat rederer

2024-04-12 16:28 UTC, ScrubN commented
> 1. For Windows GUI I think it isn't needed because Windows already asks to confirm before saving the file but I'm not sure that will cover all necessary because I'm using macOS so I will look for a solution again.

The Windows save file dialog does not delete files when a user clicks "yes". Because of that, your changes break the Windows GUI completely due to scanning `Console.In`.
![rider64_wmqsy6BIuZ (1)](https://github.com/lay295/TwitchDownloader/assets/72096833/34e963cb-35ce-43ac-a6a4-fed412c6c507)

2024-04-12 20:37 UTC, atomsbaza commented
> > 1. For Windows GUI I think it isn't needed because Windows already asks to confirm before saving the file but I'm not sure that will cover all necessary because I'm using macOS so I will look for a solution again.
> 
> The Windows save file dialog does not delete files when a user clicks "yes". Because of that, your changes break the Windows GUI completely due to scanning `Console.In`. ![rider64_wmqsy6BIuZ (1)](https://private-user-images.githubusercontent.com/72096833/322053458-34e963cb-35ce-43ac-a6a4-fed412c6c507.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTQzODcsIm5iZiI6MTcxMjk1NDA4NywicGF0aCI6Ii83MjA5NjgzMy8zMjIwNTM0NTgtMzRlOTYzY2ItMzVjZS00M2FjLWE2YTQtZmVkNDEyYzZjNTA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIwMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjg1ZjgyYjgzOWI3NTQ0Yzc3MjMyMjkwMTRiZjMzODQwZDRmNjVkNTViZmY3NjkzNTcwMGY2MDFlMjFiY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf5_oDStX1YZkrulnZvnci3zp6ywEeEeoEXNUJ259KY) [ ![rider64_wmqsy6BIuZ (1)](https://private-user-images.githubusercontent.com/72096833/322053458-34e963cb-35ce-43ac-a6a4-fed412c6c507.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTQzODcsIm5iZiI6MTcxMjk1NDA4NywicGF0aCI6Ii83MjA5NjgzMy8zMjIwNTM0NTgtMzRlOTYzY2ItMzVjZS00M2FjLWE2YTQtZmVkNDEyYzZjNTA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIwMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjg1ZjgyYjgzOWI3NTQ0Yzc3MjMyMjkwMTRiZjMzODQwZDRmNjVkNTViZmY3NjkzNTcwMGY2MDFlMjFiY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf5_oDStX1YZkrulnZvnci3zp6ywEeEeoEXNUJ259KY) ](https://private-user-images.githubusercontent.com/72096833/322053458-34e963cb-35ce-43ac-a6a4-fed412c6c507.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTQzODcsIm5iZiI6MTcxMjk1NDA4NywicGF0aCI6Ii83MjA5NjgzMy8zMjIwNTM0NTgtMzRlOTYzY2ItMzVjZS00M2FjLWE2YTQtZmVkNDEyYzZjNTA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIwMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjg1ZjgyYjgzOWI3NTQ0Yzc3MjMyMjkwMTRiZjMzODQwZDRmNjVkNTViZmY3NjkzNTcwMGY2MDFlMjFiY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf5_oDStX1YZkrulnZvnci3zp6ywEeEeoEXNUJ259KY) [ ](https://private-user-images.githubusercontent.com/72096833/322053458-34e963cb-35ce-43ac-a6a4-fed412c6c507.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTQzODcsIm5iZiI6MTcxMjk1NDA4NywicGF0aCI6Ii83MjA5NjgzMy8zMjIwNTM0NTgtMzRlOTYzY2ItMzVjZS00M2FjLWE2YTQtZmVkNDEyYzZjNTA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIwMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjg1ZjgyYjgzOWI3NTQ0Yzc3MjMyMjkwMTRiZjMzODQwZDRmNjVkNTViZmY3NjkzNTcwMGY2MDFlMjFiY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf5_oDStX1YZkrulnZvnci3zp6ywEeEeoEXNUJ259KY)




I see what happen now.
Thank you for your feedback will work in-progress

2024-05-19 14:42 UTC, atomsbaza commented
@ScrubN could you please explain more about the status disabled (--log-level None)

2024-05-20 20:44 UTC, ScrubN commented
When `--log-level None` is passed, nothing is written to stdout except for uncaught exceptions.

2024-05-21 18:36 UTC, atomsbaza commented
Thanks, @ScrubN Could you please review this PR after I complete my changes?

2024-05-24 01:11 UTC, ScrubN requested changes
You missed `TsMerge`.

2024-05-24 01:11 UTC, ScrubN commented on TwitchDownloaderCore/ChatDownloader.cs
> +
DRY - Don't repeat yourself. You have the exact same block of code in 5 different files.

2024-05-24 01:11 UTC, ScrubN commented on TwitchDownloaderCore/ChatDownloader.cs
> +                    }
`Confirm` and `Reject` aren't very common and may be difficult for some ESL users. `[Y]es`/`[N]o` is more common and already used in CacheHandler.

2024-05-24 01:11 UTC, ScrubN commented on TwitchDownloaderCore/ChatDownloader.cs
> +                    var response = Console.ReadLine()?.Trim().ToLower();
As mentioned earlier, this breaks scripts who cannot write to stdin.

2024-05-24 01:11 UTC, ScrubN commented on TwitchDownloaderCore/ChatDownloader.cs
> +        public async Task DownloadAsync(CancellationToken cancellationToken, bool allowOverwrite = true)
Why is this a method parameter when everything else is part of `...Options`.

2024-05-24 01:11 UTC, ScrubN commented on TwitchDownloaderCore/ChatDownloader.cs
> +        public async Task DownloadAsync(CancellationToken cancellationToken, bool allowOverwrite = true)
This breaks WPF tasks.

2024-05-24 01:11 UTC, ScrubN commented on TwitchDownloaderCore/ChatDownloader.cs
> +                    var response = Console.ReadLine()?.Trim().ToLower();
Why are we doing CLI specific operations in the general purpose core library?

2024-06-06 17:40 UTC, closed without merging