Add chat badges to HTML downloads
lay295/TwitchDownloader pull request #564
Opened 2023-03-01 00:08 UTC by yann-a

Hi, this is my attempt at adding chat badges to HTML downloads.

2023-03-01 00:25 UTC, yann-a commented
Some parts I'm a bit unsure of:

- When embedData is true, it should probably create a dictionnary of (_id, version) to badge instead of iterating over `chatRoot.embeddedData.twitchBadges` for every chat badge, but it's unclear for me why `chatRoot.embeddedData.twitchBadges` isn't already a dictionnary
- I think creating `BadgeResponse.cs` was necessary? It's kind of a duplicate of `Api/TwitchBadgeResponse.cs`, but it's not in the scope of the api. Also, I'm not sure of my class names there.

2023-03-03 07:01 UTC, ScrubN requested changes

2023-03-03 07:02 UTC, ScrubN commented
> but it's unclear for me why chatRoot.embeddedData.twitchBadges isn't already a dictionary

Because backwards compatibility

2023-03-05 02:53 UTC, yann-a commented on TwitchDownloaderCore/Chat/ChatHtml.cs
> +            BadgeResponse badges = await TwitchHelper.GetChatBadgesData(chatRoot.streamer.id, cancellationToken);
I actually had to add a `Dictionary<string, string> urls` property because of the different versions per badge, but done

2023-03-05 02:54 UTC, yann-a commented on TwitchDownloaderCore/TwitchHelper.cs
> +        public static async Task<BadgeResponse> GetChatBadgesData(int streamerId, CancellationToken cancellationToken = new())
Done

2023-03-05 02:54 UTC, yann-a commented on TwitchDownloaderCore/Chat/ChatHtml.cs
> +            List<string> badgesHtml = new List<string>();
Done

2023-03-05 02:57 UTC, yann-a commented
I updated the PR to use `EmbedChatBadge` and factor the `GetChatBadgesData` code. I rebased on your upstream changes because they were conflicting.

2023-03-05 03:39 UTC, ScrubN requested changes

2023-03-05 03:39 UTC, ScrubN commented on TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
> +        public Dictionary<string, string> urls { get; set; }
Add a `JsonIgnore` attribute so this isn't written to chat JSONs.
```suggestion
        [SystemText::JsonIgnore(Condition = SystemText.JsonIgnoreCondition.WhenWritingNull)]
        public Dictionary<string, string> urls { get; set; }
```

2023-03-05 03:41 UTC, ScrubN commented
Looks awesome, and chat JSONs are unaffected aside from the empty URL list. Thanks for the PR!

Also I noticed that there is a scaling issue with first party emotes. I'll fix that once this is merged.

2023-03-05 19:05 UTC, merged