Fixes #848 add CLI mode to manually concatenate ts parts
lay295/TwitchDownloader pull request #877
Opened 2023-10-28 17:23 UTC by superbonaci

Fix https://github.com/lay295/TwitchDownloader/issues/848
There's a weird github issue which looks like 2 lines were modified:
https://github.com/orgs/community/discussions/72813

2023-10-28 22:32 UTC, superbonaci commented
Looks like visual Studio for Mac introduces weird ends of line and messes up the BOM in files:
https://github.com/microsoft/vscode/issues/196905

2023-10-28 22:47 UTC, superbonaci commented
Files have to be created with Visual Studio for Windows, so will open another pull request once it's fixed.

2023-10-28 22:50 UTC, superbonaci commented
Looks like know is kind of fixed.

2023-10-28 22:58 UTC, superbonaci commented
Some of the original .cs files end in newline and other don't, so they are mixed up.

2023-11-04 00:56 UTC, ScrubN requested changes
I don't like how you had to copy-paste functions from the video downloader, however there really isn't another way until kick-support is finished and merged.

Don't get me wrong, I see value in this function and have been waiting to add it myself, but I would like tsmerge to be moved below the primary 5 functions. I do see it being used by some power users, but not nearly enough to warrant being placed above the other functions in the help text & readme.

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCLI/Program.cs
> +                .WithParsed<TsMergeArgs>(MergeTS.Merge)
Why is it placed at the top? The previous order was more or less in order of importance.

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCLI/README.md
> +  - [Arguments for mode tsmerge](#arguments-for-mode-tsmerge)
Again, it's at the top

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCLI/README.md
> +
Top again

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCLI/README.md
> +
Top again

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCore/TsMerger.cs
> +            }
this try-finally is redundant

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCore/TsMerger.cs
> +            private void VerifyDownloadedParts(List<string> videoParts, string downloadFolder, CancellationToken cancellationToken)
Nitpick: indentation

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCLI/Modes/Arguments/TsMergeArgs.cs
> +    [Verb("tsmerge", HelpText = "Concatenates (not binary) .ts/.tsv/.tsa/.m2t/.m2ts (MPEG Transport Stream) parts into another file")]
What does "Concatenates (not binary)" mean? This is not made clear to the user.

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCLI/Modes/Arguments/TsMergeArgs.cs
> +        [Option('l', "inputlist", Required = true, HelpText = "Path to input list file in text format (one part per line).")]
This is wording not very clear.

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCore/TsMerger.cs
> +            string downloadFolder = "";
`downloadFolder` is never reassigned?

2023-11-04 00:56 UTC, ScrubN commented on TwitchDownloaderCore/TsMerger.cs
> +                _progress.Report(new ProgressReport(ReportType.Log, $"The following parts appear to be invalid TS files: {string.Join(", ", failedParts)}"));
This does not discriminate between missing and corrupted files.

2023-11-04 15:08 UTC, superbonaci commented
I'll make some adjustments to it. What do you suggest instead of this line?
```
_progress.Report(new ProgressReport(ReportType.Log, $"The following parts appear to be invalid TS files: {string.Join(", ", failedParts)}"));
```

2023-11-04 18:36 UTC, ScrubN commented
> I'll make some adjustments to it. What do you suggest instead of this line?
> 
> ```
> _progress.Report(new ProgressReport(ReportType.Log, $"The following parts appear to be invalid TS files: {string.Join(", ", failedParts)}"));
> ```

Instead of dealing with discrimination, maybe remove the file exist check and let the exception propagate up. Since this is not an automatic process, the user is liable for the files existing.

2023-11-04 18:39 UTC, ScrubN requested changes

2023-11-04 18:39 UTC, ScrubN commented on TwitchDownloaderCore/TsMerger.cs
> +            await using var outputStream = new FileStream(outputFile, FileMode.Create, FileAccess.Write, FileShare.None);
```suggestion
            await using var outputStream = new FileStream(outputFile, FileMode.Create, FileAccess.Write, FileShare.Read);
```

2023-11-04 18:39 UTC, ScrubN commented on TwitchDownloaderCore/TsMerger.cs
> +                    await using (var fs = File.Open(partFile, FileMode.Open, FileAccess.Read, FileShare.None))
```suggestion
                    await using (var fs = File.Open(partFile, FileMode.Open, FileAccess.Read, FileShare.Read))
```

2023-11-12 19:47 UTC, superbonaci commented
> tsmerge to be moved below the primary 5 functions. I do see it being used by some power users, but not nearly enough to warrant being placed above the other functions in the help text & readme.

Concatenating ts parts is certainly a corner case, and for that reason most people rely on tools (like ffmpeg) that at least do something, but they don't achieve a good result. The method implemented by .NET Framework is ideal at least with the samples I've tested. So don't think it's not useful.

I'll made a new pull request with the changes you suggested, hope now they are ok.

2023-11-12 19:47 UTC, closed without merging